### ISSUE TITLE
support for in-app browser 

### ISSUE THREAD

**Issue by GorvGoyl** [ddxv/hackernews#1]
currently every link opens in an external browser new tab, I'd prefer in-app browser for that.

**Comment by ddxv** [comment]
Hello @GorvGoyl, just curious, did you mean an in-app browser within the app or within the app as well as widget?

**Comment by GorvGoyl** [comment]
i prefer using the widget so when i click on a news story from the widget it should open in an in-app browser. It would be nice if i can also go to hn comments of the story from the widget.

**Comment by ddxv** [comment]
Thanks for the clarification, I'll look into adding that.

**Comment by ddxv** [comment]
@GorvGoyl I added the in-app browser, also set it to default as there were other requests for the same feature from the Show HN post. You can pull or wait for Google to release soon. Let me know if there is any issue.

**Comment by GorvGoyl** [comment]
thanks for adding the feature. that is working but sometimes i get the following error and not sure how to resolve it:

![Screenshot_20230925-140250.png](https://github.com/ddxv/hackernews-app/assets/7106086/dda78c9d-837c-4e89-aebd-4e6d18208d1e)

**Comment by GorvGoyl** [comment]
if i click on refresh it says data loading and goes back to the same state

**Comment by GorvGoyl** [comment]
thanks, it's working!
