### ISSUE TITLE
bug: not able to click links in hn comments 


### ISSUE THREAD

**Issue by GorvGoyl** [ddxv/hackernews#3]
nothing happens when i click on the link as shown in the screenshot. it's strange that some links work while others not.

![Screenshot_20230927-014430.png](https://github.com/ddxv/hackernews-app/assets/7106086/9576dc0c-835d-4774-8c1f-6df3262d590a)

**Comment by GorvGoyl** [comment]
https://news.ycombinator.com/item?id=37663409

**Comment by ddxv** [comment]
Thanks, I can confirm this happens as well using an in app browser. Hopefully it is a know issue with inapp browsers.

**Comment by ddxv** [comment]
@GorvGoyl code is updated on github and also sending to store, a couple things changed, please let me know if you see the link issue again. Going back to look for it I was able to click all links, but not sure if it was something specific to certain kinds of links I didn't try.

**Comment by GorvGoyl** [comment]
Thanks @ddxv I'm using your app on a daily basis (love that widget). will let you know if I find any issues.

Couple of suggestions (nothing major):
- How frequently does the widger refresh for stories?.. I'd prefer if it refreshes every 4 hours (to reduce battery consumption)..  i can always refresh it on demand by reload btn. better if ther's an option to set refresh period.
- ability to set maximum stories on Widget.. I'd prefer to be 30 stories max.
- indicate hot stories (either 300+ upvotes or 100+ comments).. it could be shown by making **upvote points** / **comments** bolder.

**Comment by ddxv** [comment]
Thanks, just following up on those suggestions. Is there one of those that is more important than others, perhaps setting the refresh interval?

**Comment by GorvGoyl** [comment]
yes refresh interval would be nice but before that I realise there's no way to copy the article link if the in-app browser is set. I'd like to have some way to copy news article link and hn story link.
